Adding KitcheSink Example

diff --git a/.github/workflows/test-app.yml b/.github/workflows/test-app.yml
--- a/.github/workflows/test-app.yml
+++ b/.github/workflows/test-app.yml
@@ -1,342 +1,200 @@
-# name: Cypress Tests
+# GitHub Actions
+# https://help.github.com/en/articles/configuring-a-workflow
+# good list of examples at http://www.thedreaming.org/2019/09/10/github-ci/
+name: Cypress parallel tests
 
-# on: [push]
-
-# jobs:
-#   cypress-run:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v2
-#       # Install NPM dependencies, cache them correctly
-#       # and run all Cypress tests
-#       - name: Cypress run
-#         uses: cypress-io/github-action@v2
-#         with:
-#           build: npm run build
-#           start: npm start
-#           record: true
-#         env:
-#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-name: Cypress Tests
-
-on:
-  push:
-    branches-ignore:
-      - "renovate/**"
+on: push
 
 jobs:
   install:
-    runs-on: ubuntu-latest
-    container:
-      image: cypress/browsers:node16.13.0-chrome95-ff94
-      options: --user 1001
+    name: Install NPM and Cypress
+    runs-on: ubuntu-18.04
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      - uses: actions/checkout@master
 
-      - name: Cypress install
-        uses: cypress-io/github-action@v4
+      # install a specific version of Node using
+      # https://github.com/actions/setup-node
+      - name: Use Node.js v12
+        uses: actions/setup-node@v1
         with:
-          runTests: false
-      # report machine parameters
-      - run: yarn cypress info
-      - run: node --version
-      - run: node -p 'os.cpus()'
-      # - run: yarn types
-      # - run: yarn lint
-      # - run: yarn test:unit:ci
-      # - run: npm run build
+          node-version: 12
 
-      # - name: Save build folder
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: dist
-      #     if-no-files-found: error
-      #     path: dist
+      # just so we learn about available environment variables GitHub provides
+      - name: Print CI env variables
+        run: |
+          npm i -g @bahmutov/print-env@2
+          print-env GITHUB BUILD ACTIONS || true
 
-  ui-chrome-tests:
-    timeout-minutes: 15
-    runs-on: ubuntu-latest
-    container:
-      image: cypress/browsers:node16.13.0-chrome95-ff94
-      options: --user 1001
-    needs: install
-    strategy:
-      # when one test fails, DO NOT cancel the other
-      # containers, because this will kill Cypress processes
-      # leaving the Dashboard hanging ...
-      # https://github.com/cypress-io/github-action/issues/48
-      fail-fast: false
-      matrix:
-        # run copies of the current job in parallel
-        containers: [1]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      # - name: Download the build folders
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: dist
-      #     path: dist
-
-      - name: Cypress info
-        run: npx cypress info
-
-      - name: Node info
-        run: node -v
-
-      - name: __e Dir
-        run: ls /__e
-
-      - name: "UI Tests - Chrome"
-        uses: cypress-io/github-action@v4
+      # Restore the previous NPM modules and Cypress binary archives.
+      # Any updated archives will be saved automatically after the entire
+      # workflow successfully finishes.
+      # See https://github.com/actions/cache
+      # we use exact restore key to avoid NPM module snowballing
+      # https://glebbahmutov.com/blog/do-not-let-npm-cache-snowball/
+      - name: Cache central NPM modules
+        uses: actions/cache@v1
         with:
-          start: npm run cypress:run
-          # wait-on: "http://localhost:8080"
-          # wait-on-timeout: 120
-          browser: chrome
-          record: true
-          parallel: true
-          group: "UI - Chrome"
-          spec: cypress/integration/features/**
-          config-file: cypress.json
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+
+      # we use the exact restore key to avoid Cypress binary snowballing
+      # https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/
+      - name: Cache Cypress binary
+        uses: actions/cache@v1
+        with:
+          path: ~/.cache/Cypress
+          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+          restore-keys: |
+            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+
+      # Cache local node_modules to pass to testing jobs
+      - name: Cache local node_modules
+        uses: actions/cache@v1
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-modules-${{ github.ref }}-
+
+      - name: install dependencies and verify Cypress
         env:
-          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
-          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-          # Recommended: pass the GitHub token lets this action correctly
-          # determine the unique run id necessary to re-run the checks
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          DEBUG: "cypress:server:args"
+          # make sure every Cypress install prints minimal information
+          CI: 1
+        run: |
+          npm ci
+          npx cypress cache path
+          npx cypress cache list
+          npx cypress verify
+          npx cypress info
 
-  ui-chrome-other-tests:
-    timeout-minutes: 15
-    runs-on: ubuntu-latest
-    container:
-      image: cypress/browsers:node16.13.0-chrome95-ff94
-      options: --user 1001
+  # Duplicate job definitions - GitHub YAML does not support
+  # anchor definitions yet, thus we cannot put same steps into a template object yet
+  test1:
+    name: Cypress test 1
+    runs-on: ubuntu-18.04
     needs: install
-    strategy:
-      # when one test fails, DO NOT cancel the other
-      # containers, because this will kill Cypress processes
-      # leaving the Dashboard hanging ...
-      # https://github.com/cypress-io/github-action/issues/48
-      fail-fast: false
-      matrix:
-        # run copies of the current job in parallel
-        containers: [1]
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      - uses: actions/checkout@master
 
-      # - name: Download the build folders
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: dist
-      #     path: dist
-
-      - name: Cypress info
-        run: npx cypress info
-
-      - name: Node info
-        run: node -v
-
-      - name: __e Dir
-        run: ls /__e
-
-      - name: "UI Tests Others - Chrome"
-        uses: cypress-io/github-action@v4
+      # install a specific version of Node using
+      # https://github.com/actions/setup-node
+      - name: Use Node.js v12
+        uses: actions/setup-node@v1
         with:
-          start: npm run cypress:run
-          browser: chrome
-          record: true
-          parallel: true
-          group: "UI - Chrome"
-          spec: cypress/integration/features/**/*
-          config-file: cypress.json
+          node-version: 12
+
+      # Restore just local node_modules and the Cypress binary archives.
+      - name: Cache Cypress binary
+        uses: actions/cache@v1
+        with:
+          path: ~/.cache/Cypress
+          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+          restore-keys: |
+            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+
+      - name: Cache local node_modules
+        uses: actions/cache@v1
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-modules-${{ github.ref }}-
+
+      # check the restored Cypress binary
+      - name: Check binary
+        run: |
+          npx cypress cache path
+          npx cypress cache list
+
+      # Starts local server, then runs Cypress tests and records results on the dashboard
+      - name: Cypress tests
+        run: |
+          npm start &
+          npx cypress:run --record --parallel --group "Parallel 2x"
         env:
-          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
+          # place your secret record key at
+          # https://github.com/cypress-io/cypress-example-kitchensink/settings/secrets
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-          # Recommended: pass the GitHub token lets this action correctly
-          # determine the unique run id necessary to re-run the checks
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          DEBUG: "cypress:server:args"
-  # ui-chrome-mobile-tests:
-  #   timeout-minutes: 15
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image: cypress/browsers:node16.13.0-chrome95-ff94
-  #     options: --user 1001
-  #   needs: install
-  #   strategy:
-  #     # when one test fails, DO NOT cancel the other
-  #     # containers, because this will kill Cypress processes
-  #     # leaving the Dashboard hanging ...
-  #     # https://github.com/cypress-io/github-action/issues/48
-  #     fail-fast: false
-  #     matrix:
-  #       # run copies of the current job in parallel
-  #       containers: [1, 2, 3, 4, 5]
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
+          TERM: xterm
 
-  #     - name: Download the build folders
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: dist
+      # Save videos and screenshots as test artifacts
+      # https://github.com/actions/upload-artifact
+      - uses: actions/upload-artifact@master
+        # there might be no screenshots created when:
+        # - there are no test failures
+        # so only upload screenshots if previous step has failed
+        if: failure()
+        with:
+          name: screenshots
+          path: cypress/screenshots
+      # video should always be generated
+      - uses: actions/upload-artifact@master
+        with:
+          name: videos
+          path: cypress/videos
 
-  #     - name: "UI Tests - Chrome - Mobile"
-  #       uses: cypress-io/github-action@v4
-  #       with:
-  #         config: "viewportWidth=375,viewportHeight=667"
-  #         start: npm run start
-  #         wait-on: "http://localhost:3000"
-  #         wait-on-timeout: 120
-  #         browser: chrome
-  #         record: true
-  #         parallel: true
-  #         group: "UI - Chrome - Mobile"
-  #         spec: cypress/integration/*
-  #         config-file: cypress.config.js
-  #       env:
-  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
-  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-  #         # Recommended: pass the GitHub token lets this action correctly
-  #         # determine the unique run id necessary to re-run the checks
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  test2:
+    name: Cypress test 2
+    runs-on: ubuntu-18.04
+    needs: install
+    steps:
+      - uses: actions/checkout@master
 
-  # ui-firefox-tests:
-  #   timeout-minutes: 15
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image: cypress/browsers:node16.13.0-chrome95-ff94
-  #     options: --user 1001
-  #   needs: install
-  #   strategy:
-  #     # when one test fails, DO NOT cancel the other
-  #     # containers, because this will kill Cypress processes
-  #     # leaving the Dashboard hanging ...
-  #     # https://github.com/cypress-io/github-action/issues/48
-  #     fail-fast: false
-  #     matrix:
-  #       # run copies of the current job in parallel
-  #       containers: [1, 2, 3, 4, 5]
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
+      # install a specific version of Node using
+      # https://github.com/actions/setup-node
+      - name: Use Node.js v12
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12
 
-  #     - name: Download the build folders
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: dist
+      # Restore just local node_modules and the Cypress binary archives.
+      - name: Cache Cypress binary
+        uses: actions/cache@v1
+        with:
+          path: ~/.cache/Cypress
+          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+          restore-keys: |
+            cypress-${{ runner.os }}-cypress-${{ github.ref }}-
 
-  #     - name: "UI Tests - Firefox"
-  #       uses: cypress-io/github-action@v4
-  #       with:
-  #         start: npm run start
-  #         wait-on: "http://localhost:3000"
-  #         wait-on-timeout: 120
-  #         browser: firefox
-  #         record: true
-  #         parallel: true
-  #         group: "UI - Firefox"
-  #         spec: cypress/integration/*
-  #         config-file: cypress.config.js
-  #       env:
-  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
-  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-  #         # Recommended: pass the GitHub token lets this action correctly
-  #         # determine the unique run id necessary to re-run the checks
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Cache local node_modules
+        uses: actions/cache@v1
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-modules-
 
-  # ui-firefox-mobile-tests:
-  #   timeout-minutes: 15
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image: cypress/browsers:node16.13.0-chrome95-ff94
-  #     options: --user 1001
-  #   needs: install
-  #   strategy:
-  #     # when one test fails, DO NOT cancel the other
-  #     # containers, because this will kill Cypress processes
-  #     # leaving the Dashboard hanging ...
-  #     # https://github.com/cypress-io/github-action/issues/48
-  #     fail-fast: false
-  #     matrix:
-  #       # run copies of the current job in parallel
-  #       containers: [1, 2, 3, 4, 5]
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
+      # check the restored Cypress binary
+      - name: Check binary
+        run: |
+          npx cypress cache path
+          npx cypress cache list
 
-  #     - name: Download the build folders
-  #       uses: actions/download-artifact@v3
-  #       with:
-      #     name: dist
-      #     path: dist
+      # Starts local server, then runs Cypress tests and records results on the dashboard
+      - name: Cypress tests
+        run: |
+          npm start &
+          npx cypress:run --record --parallel --group "Parallel 2x"
+        env:
+          # place your secret record key at
+          # https://github.com/cypress-io/cypress-example-kitchensink/settings/secrets
+          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+          TERM: xterm
 
-      # - name: "UI Tests - Firefox - Mobile"
-      #   uses: cypress-io/github-action@v4
-      #   with:
-      #     config: "viewportWidth=375,viewportHeight=667"
-      #     start: npm run start
-      #     wait-on: "http://localhost:3000"
-      #     wait-on-timeout: 120
-      #     browser: firefox
-      #     record: true
-      #     parallel: true
-      #     group: "UI - Firefox - Mobile"
-      #     spec: cypress/integration/*
-      #     config-file: cypress.config.js
-      #   env:
-      #     CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
-      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-      #     # Recommended: pass the GitHub token lets this action correctly
-      #     # determine the unique run id necessary to re-run the checks
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  # ui-windows-tests:
-  #   timeout-minutes: 40
-  #   runs-on: windows-2019
-  #   needs: install-windows
-  #   strategy:
-  #     # when one test fails, DO NOT cancel the other
-  #     # containers, because this will kill Cypress processes
-  #     # leaving the Dashboard hanging ...
-  #     # https://github.com/cypress-io/github-action/issues/48
-  #     fail-fast: false
-  #     matrix:
-  #       # run copies of the current job in parallel
-  #       containers: [1, 2, 3, 4, 5]
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v3
-
-  #     - name: Download the build folders
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: dist
-
-  #     - name: "UI Tests - Electron - Windows"
-  #       uses: cypress-io/github-action@v4
-  #       with:
-  #         start: npm run start
-  #         wait-on: "http://localhost:3000"
-  #         wait-on-timeout: 120
-  #         record: true
-  #         parallel: true
-  #         group: "UI - Electron - Windows"
-  #         spec: cypress/integration/*
-  #         config-file: cypress.config.js
-  #       env:
-  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
-  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-  #         # Recommended: pass the GitHub token lets this action correctly
-  #         # determine the unique run id necessary to re-run the checks
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # Save videos and screenshots as test artifacts
+      # https://github.com/actions/upload-artifact
+      - uses: actions/upload-artifact@master
+        # there might be no screenshots created when:
+        # - there are no test failures
+        # so only upload screenshots if previous step has failed
+        if: failure()
+        with:
+          name: screenshots
+          path: cypress/screenshots
+      # video should always be generated
+      - uses: actions/upload-artifact@master
+        with:
+          name: videos
+          path: cypress/videos
